import React,{useContext,useMemo,useState} from 'react';
import {Search,ExternalLink} from 'lucide-react';
import {LocaleContext,translate} from '../utils/i18n.js';
import {museumWorksFor,museums,catalogueDate} from '../utils/museum-catalog.js';
export default function MuseumWorks({artist,onOpen,Image,favoriteButton}){
 const locale=useContext(LocaleContext);const t=s=>translate(s,locale);
 const [query,setQuery]=useState('');const [source,setSource]=useState('all');const [limit,setLimit]=useState(12);
 const works=useMemo(()=>museumWorksFor(artist.id),[artist.id]);
 const filtered=works.filter(p=>(source==='all'||p.museum===source)&&`${p.title} ${p.date} ${p.attribution}`.toLocaleLowerCase(locale).includes(query.toLocaleLowerCase(locale)));
 return <section className="museum-works" aria-label={t('Музейный каталог')}><div className="museum-heading"><h3>{t('Музейный каталог')} <small className="catalog-count">{works.length}</small></h3><span>{t('Обновлено')}: {catalogueDate}</span></div><p className="secondary-note">{t('Все доступные записи живописи из подключённых коллекций. Это не полный каталог творчества художника. Названия сохранены на языке музея.')}</p>{works.length>0&&<><label className="museum-search"><Search size={16}/><input aria-label={t('Поиск в музейном каталоге')} placeholder={t('Название или год')} value={query} onChange={e=>{setQuery(e.target.value);setLimit(12);}}/></label><div className="museum-filters" role="group" aria-label={t('Музей')}><button aria-pressed={source==='all'} onClick={()=>{setSource('all');setLimit(12);}}>{t('Все')}</button>{Object.entries(museums).filter(([id])=>works.some(p=>p.museum===id)).map(([id,name])=><button key={id} aria-pressed={source===id} onClick={()=>{setSource(id);setLimit(12);}}>{name}</button>)}</div><p className="catalog-result" role="status">{t('Найдено работ')}: {filtered.length}</p><div className="museum-grid">{filtered.slice(0,limit).map(p=><article key={p.id}><button className="museum-card" onClick={()=>onOpen(p.id)}><div className="museum-card-image"><Image painting={p} loading="lazy"/></div><span><strong>{p.title}</strong><small>{p.date}</small><em>{p.sourceName}</em></span></button>{favoriteButton('paintings',p.id,p.title)}</article>)}</div>{!filtered.length&&<p>{t('Ничего не найдено')}</p>}{limit<filtered.length&&<button className="primary-button" onClick={()=>setLimit(v=>v+12)}>{t('Показать ещё')}</button>}</>}<a className="source-link" href={artist.source} target="_blank" rel="noreferrer">{t('Продолжить в музейном каталоге')}<ExternalLink size={14}/></a></section>;
}
